// <auto-generated />
using System;
using BookStore.Core.Enums;
using BookStore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStore.Presentation.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200531184212_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BookStore.Core.Models.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET latin1");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookStore.Core.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET latin1");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET latin1");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET latin1");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<byte>("Type");
                });

            modelBuilder.Entity("BookStore.Core.Models.Entities.Librarian", b =>
                {
                    b.HasBaseType("BookStore.Core.Models.Entities.User");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET latin1");

                    b.Property<DateTime>("LastLogged")
                        .HasColumnType("datetime(6)");

                    b.HasDiscriminator().HasValue((byte)1);
                });

            modelBuilder.Entity("BookStore.Core.Models.Entities.Subscriber", b =>
                {
                    b.HasBaseType("BookStore.Core.Models.Entities.User");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET latin1");

                    b.Property<string>("Cnp")
                        .HasColumnType("longtext CHARACTER SET latin1");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET latin1");

                    b.HasDiscriminator().HasValue((byte)0);
                });

            modelBuilder.Entity("BookStore.Core.Models.Entities.Book", b =>
                {
                    b.HasOne("BookStore.Core.Models.Entities.User", "User")
                        .WithMany("Books")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
